# Generated by Django 2.2.4 on 2020-06-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoLottoBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(max_length=20)),
                ('number_1', models.CharField(max_length=20)),
                ('number_2', models.CharField(max_length=20)),
                ('number_3', models.CharField(max_length=20)),
                ('number_4', models.CharField(max_length=20)),
                ('number_5', models.CharField(max_length=20)),
                ('number_6', models.CharField(max_length=20)),
                ('number_7', models.CharField(max_length=20)),
            ],
        ),
    ]
