# Generated by Django 2.2.4 on 2020-06-08 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_lotto_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DjangoLottoBoard',
            new_name='lottoBoard',
        ),
    ]
