# Generated by Django 2.2.4 on 2020-06-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_lotto_app', '0003_auto_20200615_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottoboard',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
